import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import backgroundImage from "public/assests/herobg.png";
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className='gradient'></div>
        <Navbar></Navbar>
        {children}</body>
    </html>
  )
}
